import localFont from "next/font/local";

import "./globals.css";

const myFont = localFont({ src: "../public/fonts/IRANSansWeb.woff2" });
export const metadata = {
  title: "Game world",
  description: "Generated by create next app",
};

export default function RootLayout({ children, auth, game }) {
  return (
    <html lang="en" className={myFont.className}>
      <body className="overflow-x-hidden">
        {game}
        {auth}
        {children}
      </body>
    </html>
  );
}
